apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: app-web-hpa
  namespace: escalabilidad-lab
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: app-web-solucion
  minReplicas: 3        # Mínimo 3 pods
  maxReplicas: 10       # Máximo 10 pods
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70  # Escalar cuando CPU > 70%
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80  # Escalar cuando memoria > 80%
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
      - type: Percent
        value: 50
        periodSeconds: 60
    scaleUp:
      stabilizationWindowSeconds: 30
      policies:
      - type: Percent
        value: 100
        periodSeconds: 30