apiVersion: v1
kind: Service
metadata:
  name: app-web-service-solucion
  namespace: escalabilidad-lab
spec:
  selector:
    app: web-app-solucion
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80